services:
  - type: web
    name: dentscan-ai-nemophila
    runtime: docker
    plan: free
    region: singapore
    repo: https://github.com/kla2009k/Dent_AI
    branch: main
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /api/health
    autoDeployTrigger: checksPass
    envVars:
      - key: INFERENCE_BACKEND
        value: onnx
